networks:
  default:
    external:
      name: dy
services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=shopinvader-docky.dy
      - VIRTUAL_PORT=8069
      - DEMO=True
      - ADDONS_PATH=/opt/odoo/local-src,/opt/odoo/src/addons,/opt/odoo/links,/opt/odoo/external-src/web,/opt/odoo/external-src/bank-payment,/opt/odoo/external-src/account-fiscal-rule,/opt/odoo/external-src/reporting-engine,/opt/odoo/external-src/l10n-brazil,/opt/odoo/external-src/server-tools
    links:
      - db
    networks:
      default:
        aliases:
          - shopinvader-docky.dy
    volumes:
      - ./odoo:/opt/odoo
version: '3'
